# Практическое занятие 8
# Компьютерный практикум по алгебре на Python
## Численное решение систем линейных алгебраических уравнений (СЛАУ) с numpy.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [ ]:
import numpy as np
from numpy import linalg

### Задание 1.
Решить СЛАУ с помощью linalg.solve() и выполнить проверку.
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+5z=10
\end{matrix}
\right.
$$

In [ ]:
def main():
  a_matrix = np.array((
      (-1, 5, -3),
      (4, -1, 5),
      (3, 4, 5),
  ))
  b_matrix = np.array([8, -1, 10])
  print(f"Решения: {tuple(linalg.solve(a_matrix, b_matrix))}")

if __name__ == "__main__":
  main()

Решения: (-1.0, 2.0, 1.0)


### Задание 2.
Определить с помощью Теоремы Кронекера-Капелли и linalg.matrix_rank, совместна ли СЛАУ
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+2z=7
\end{matrix}
\right.
$$

Сделать вывод о числе решений (текстом)

In [ ]:
def main():
  a_matrix = np.array((
      (-1, 5, -3),
      (4, -1, 5),
      (3, 4, 2),
  ))
  b_matrix = np.array([8, -1, 7])
  ab_matrix = np.column_stack((a_matrix, b_matrix))

  print(f"Ранг rk(А) = {linalg.matrix_rank(a_matrix)}")
  print(f"Ранг rk(Аb) = {linalg.matrix_rank(ab_matrix)}")
  print("=> по теореме Кронекера-Капелли СЛАУ имеет решение")
  print(f"Матрица имеет {'1 решение' if a_matrix.shape[1] == linalg.matrix_rank(a_matrix) else 'бесконечно много решений'}")

if __name__ == "__main__":
  main()

Ранг rk(А) = 2
Ранг rk(Аb) = 2
=> по теореме Кронекера-Капелли СЛАУ имеет решение
Матрица имеет бесконечно много решений


### Задание 3.
Исследовать на совместность СЛАУ с параметром $a$ при значениях параметра $a=1$ и $a=-1$ и найти решение, если оно единственно и провести проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+5y-3z=8a\\
4x-ay+5z=-a\\
3x+4y+2z=5a
\end{matrix}
\right.
$$

In [ ]:
def solve_matrix(a: int):
  a_matrix = np.array((
    (-1, 5, -3),
    (4, -a, 5),
    (3, 4, 2),
  ))
  b_matrix = np.array([8*a, -a, 5*a])
  ab_matrix = np.column_stack((a_matrix, b_matrix))

  print(f"При a = {a}:")
  rk_a = linalg.matrix_rank(a_matrix)
  rk_ab = linalg.matrix_rank(ab_matrix)
  if rk_a == rk_ab:
    print(f"Матрица имеет решения")
    if a_matrix.shape[1] == rk_a:
      print(f"Матрица имеет единственное решение:")
      print(tuple(linalg.solve(a_matrix, b_matrix)))
    else:
      print(f"Матрица имеет более 1 решения")
  else:
    print(f"Матрица не имеет решений")
  print()

def main():
  for a in (-1, 1):
    solve_matrix(a)

if __name__ == "__main__":
  main()

При a = -1:
Матрица имеет решения
Матрица имеет единственное решение:
(-1.2857142857142863, -0.9999999999999998, 1.428571428571429)

При a = 1:
Матрица не имеет решений



### Задание 4
В расширенной матрице СЛАУ из Задания 2 

1) выделить матрицу левой части

2) выделить столбец правой части

3) транспонировать матрицу, полученную в 1)

4) получить расширенную матрицу из матрицы 3) и столбца 2)

5) создать на основе списочного выражения np.array $3\times 4$ из расположенных в шахматном порядке чисел 1 и $-1$.

In [ ]:
def main():
  ab_matrix = np.array((
      (-1, 5, -3, 8),
      (4, -1, 5, -1),
      (3, 4, 2, 7),
  ))

  left_matrix = ab_matrix[:, :-1]
  print(f"Матрица левой части:\n{left_matrix}")
  
  right_column = ab_matrix[:, -1]
  print(f"Столбец правой части:\n{right_column}")

  transposed_l_matrix = np.transpose(left_matrix)
  print(f"Транспонированная матрица левой части:\n{transposed_l_matrix}")

  extended_matrix = np.column_stack((transposed_l_matrix, right_column))
  print(f"Новая расширенная матрица:\n{extended_matrix}")

  n, m = 3, 4
  # Также можно написать (-1)**(i + j), но возведение в степень происходить дольше.
  chess_order_matrix = np.array([[1 - 2 * ((i + j) % 2) for j in range(m)] for i in range(n)])
  print(f"Матрица {n} x {m} из чисел -1 и 1 в шахматном порядке:\n{chess_order_matrix}")

if __name__ == "__main__":
  main()

Матрица левой части:
[[-1  5 -3]
 [ 4 -1  5]
 [ 3  4  2]]
Столбец правой части:
[ 8 -1  7]
Транспонированная матрица левой части:
[[-1  4  3]
 [ 5 -1  4]
 [-3  5  2]]
Новая расширенная матрица:
[[-1  4  3  8]
 [ 5 -1  4 -1]
 [-3  5  2  7]]
Матрица 3 x 4 из чисел -1 и 1 в шахматном порядке:
[[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]]


### Индивидуальное задание.
Исследовать на совместность СЛАУ с параметром $a$ при заданных значениях параметра $a$ и найти решение, если оно единственно и провести проверку подстановкой.
 

N 50
\begin{align*}
 A = \left[\begin{matrix}9 & -1 & a & 4\\1 & -7 & -7 & 9\\8 & 2 & -1 & 6\\-10 & 4 & -9 & -2\end{matrix}\right],
    \qquad b = \left[\begin{matrix}43\\-125\\-9\\-77\end{matrix}\right], \alpha = 4, \alpha = 5. 
 \end{align*}

In [ ]:
def solve_matrix(a: int):
  a_matrix = np.array((
      (9, -1, a, 4),
      (1, -7, -7, 9),
      (8, 2, -1, 6),
      (-10, 4, -9, -2)
  ))
  b_column = np.array([43, -125, -9, -77])
  ab_matrix = np.column_stack((a_matrix, b_column))

  print(f"При a = {a}:")
  rk_a = linalg.matrix_rank(a_matrix)
  rk_ab = linalg.matrix_rank(ab_matrix)
  print(f"Ранг rk(A) = {rk_a}.\tРанг rk(Ab) = {rk_ab}")
  
  if rk_a != rk_ab:
    print("СЛАУ несовместна\n")
    return
  
  if a_matrix.shape[1] != rk_a:
    print("СЛАУ имеет более 1 решения\n")
    return

  print("СЛАУ имеет 1 решение:")
  print(linalg.solve(a_matrix, b_column))

def main():
  for a in (4, 5):
    solve_matrix(a)

if __name__ == "__main__":
  main()

При a = 4:
Ранг rk(A) = 3.	Ранг rk(Ab) = 4
СЛАУ несовместна

При a = 5:
Ранг rk(A) = 4.	Ранг rk(Ab) = 4
СЛАУ имеет 1 решение:
[ 2.  4.  9. -4.]
